### ISSUE TITLE
README doesn’t give any documentation on how to turn pi-btaudio off

### ISSUE THREAD

**Issue by Cin316** [bablokb/pi-btaudio#1]
The README doesn’t give any information on how you can temporarily disable pi-btaudio (so normal audio can work again) or how to uninstall the tool.  I ended up having to do a clean install on my Pi because I broke the sound using this tool.

How can I uninstall or temporarily disable this tool?

**Comment by bablokb** [comment]
Well this is just Linux standard. Like any other service, you can stop and/or disable the service with

sudo systemctl stop pi-btaudio.service
sudo systemctl disable pi-btaudio.service

If you really want to uninstall the service, just remove all files you find underneath files/ in the source project - they are copied 1:1 to the system.

Bernhard

**Comment by bablokb** [comment]
btw. normal audio still works, even with pi-btaudio installed and active. You just have to edit the /etc/asound.conf and revert to the defaults. Or just add your normal soundcard as second device. Just google about alsa configuration. It is not trivial, but you certainly find a lot of helpful documents.
