### ISSUE TITLE
My experience w/ BT audio on RPi OS 'bookworm'

### ISSUE THREAD

**Issue by seamusdemora** [bablokb/pi-btaudio#13]
Hello - I've followed your repo for some time, and generally agree with your recommendations. However, I'd like to suggest something different for ***some*** of the RPi hardware. My experience is limited to the RPi Zero 2W and RPi 3A+; in both cases I run these systems from the "Lite" 'bookworm' distro (i.e. `armhf`). 

What I've found is that installing the `pipewire` packages from Debian's `bookworm-backports` has been the "key to happiness". 

Recently, `bookworm-backports` yields a `pipewire` version of 1.2.1, and a `wireplumber` version of 0.4.17. 

I also believe the RPi BT hardware has issues (_e.g._ BT & WiFi share a single antenna). In testing to date on a Zero 2W, only the backported `pipewire` packages have been able to overcome these issues and deliver reliable, high-quality sound. Testing on the 3A+ with the default `pipewire` packages has required an external USB BT "dongle" to achieve the same level of reliability & sound quality. 

I initially tried 'bluez-alsa' - as you have suggested. It was a significant improvement over all other solutions (for a while), but for me & my systems, it falls a bit short of `pipewire` for connection reliability. It may also interest you to know that [Debian now has a bluez-alsa ***package***](https://packages.debian.org/stable/bluez-alsa-utils). I've not been motivated to try this b/c the backported `pipewire` is operating so well. 

And finally, I share your views wrt the *"complications"* of getting BT audio working in Linux... it is far more complicated than it should be!

**Comment by bablokb** [comment]
Thanks for the contribution! I must admit that I haven't recently updated any systems, so I have no personal experience with pipewire. But everything I read about it sounds promising. I only hope that pipewire will be more stable across different OS-releases. That was one of the core problems with bluez-alsa: it sometimes worked great only to fail after an update of the base system.

**Comment by bablokb** [comment]
Updated the readme to point to this issue.

**Comment by seamusdemora** [comment]
> Thanks for the contribution! I must admit that I haven't recently updated any systems, so I have no personal experience with pipewire. But everything I read about it sounds promising. I only hope that pipewire will be more stable across different OS-releases. That was one of the core problems with bluez-alsa: it sometimes worked great only to fail after an update of the base system.

I cannot answer the question re `pipewire` stability across different releases as I have no experience I could call relevant. I suppose all we can do is keep our "fingers crossed"  :) 

I do think the `bluez-alsa` guys are very competent - and super helpful (I've asked a lot of questions :)   I'd love to use it - it's significantly *"lighter weight"* than `pipewire`, but it's just not as reliable - on my systems. And so far, I've been unable to get them interested into looking into the issue deeper (it may well be that the RPi hardware/firmware is the culprit!). 

And please feel free to close this "issue" whenever you like.

**Comment by seamusdemora** [comment]
Just another *quick* update: `pipewire` continues to work superbly on my systems, **BUT :** 

If you're following `backports` in `/etc/sources.list`, know that a recent upgrade destroyed my BT setup. As it turns out, this was caused by the `wireplumber` from `backports`. The easiest thing to do for now may be to remove the `backports` listing from `/etc/sources.list`. I'm sure this will be fixed, but ***when*** is an unknown.
