### ISSUE TITLE
can't access BT audio nor as default car nor visible from snap cast client

### ISSUE THREAD

**Issue by karba78** [bablokb/pi-btaudio#2]
installed pi-btaudio
pi3 connect perfectly on startup but not set as default nor visible sound output by system
desktop sound icon shows 3 choices Analog, HDMI, BT Speaker(checked)
had changed asound.conf as follows
amixer bluealsa shows the right BT speaker see bottom
feel paulseaudio might be messing up things

pcm.!default "bluealsa"
ctl.!default "bluealsa"
defaults.bluealsa.interface "hci0"
defaults.bluealsa.device "00:0C:8A:5D:42:11"
defaults.bluealsa.profile "a2dp"

the sound continues to be directed to default device
snap client does not see bluealsa output; 
see output below

snapclient -l
0: null
Discard all samples (playback) or generate zero samples (capture)

1: jack
JACK Audio Connection Kit

2: pulse
PulseAudio Sound Server

3: default
Playback/recording through the PulseAudio sound server

4: sysdefault:CARD=ALSA
bcm2835 ALSA, bcm2835 ALSA
Default Audio Device

5: dmix:CARD=ALSA,DEV=0
bcm2835 ALSA, bcm2835 ALSA
Direct sample mixing device

6: dmix:CARD=ALSA,DEV=1
bcm2835 ALSA, bcm2835 IEC958/HDMI
Direct sample mixing device

7: dmix:CARD=ALSA,DEV=2
bcm2835 ALSA, bcm2835 IEC958/HDMI1
Direct sample mixing device

8: dsnoop:CARD=ALSA,DEV=0
bcm2835 ALSA, bcm2835 ALSA
Direct sample snooping device

9: dsnoop:CARD=ALSA,DEV=1
bcm2835 ALSA, bcm2835 IEC958/HDMI
Direct sample snooping device

10: dsnoop:CARD=ALSA,DEV=2
bcm2835 ALSA, bcm2835 IEC958/HDMI1
Direct sample snooping device

11: hw:CARD=ALSA,DEV=0
bcm2835 ALSA, bcm2835 ALSA
Direct hardware device without any conversions

12: hw:CARD=ALSA,DEV=1
bcm2835 ALSA, bcm2835 IEC958/HDMI
Direct hardware device without any conversions

13: hw:CARD=ALSA,DEV=2
bcm2835 ALSA, bcm2835 IEC958/HDMI1
Direct hardware device without any conversions

14: plughw:CARD=ALSA,DEV=0
bcm2835 ALSA, bcm2835 ALSA
Hardware device with all software conversions

15: plughw:CARD=ALSA,DEV=1
bcm2835 ALSA, bcm2835 IEC958/HDMI
Hardware device with all software conversions

16: plughw:CARD=ALSA,DEV=2
bcm2835 ALSA, bcm2835 IEC958/HDMI1
Hardware device with all software conversions

17: usbstream:CARD=ALSA
bcm2835 ALSA
USB Stream Output

pi@raspberrypi:~

amixer -D bluealsa
Simple mixer control 'Bose SoundLink Mobile - A2DP',0
  Capabilities: pvolume pswitch
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 127
  Mono:
  Front Left: Playback 127 [100%] [on]
  Front Right: Playback 127 [100%] [on]

**Comment by bablokb** [comment]
Hm this project is explicitly for headless Raspian. The desktop bluetooth managment applications have their own ideas about defaults, so setting the default in /etc/asound.conf is probably overridden somewhere else.

**Comment by bdorer** [comment]
hmm, I'm new to this. If I'm right pulseaudio isn't able to work with bluealsa. If you want bluetooth with pulseaudio you need pulseaudio-modulebluetooth. In this case this project isn't what you want.

**Comment by bablokb** [comment]
Exactly.
