### ISSUE TITLE
Speaker not connected at boot

### ISSUE THREAD

**Issue by stefanofornari** [bablokb/pi-btaudio#4]
Hello, after following the procedure, I rebooted my Raspebbry PI 2B but the device did not connect automatically. Also, I am not sure it is the default now. omxplayer -o alsa does not reproduce any sound, same for aplay.

How can I help troubleshooting?

**Comment by bablokb** [comment]
The Pi2B does not have bluetooth. Did you use an usb-bluetooth-dongle?

**Comment by stefanofornari** [comment]
Yep, and it connects when I re-switch the speaker on.

**Comment by bablokb** [comment]
One part of this project is the service pi-btaudio.service. This is a python-script that waits for bt-events and tries to connect to the configured device. Sometime between the time of writing the script and now the dbus/bt-interface has changed, and I think it does not work anymore as expected. One problem is that the interface is not really documented. 

The service actually also tries to manually connect to the configured device (using bluetoothctl), but if this also doesn't work, it might be a problem of your speaker. Maybe it only advertises itself after power on. BT is very hard to debug, there are some sniffer like tools which you could use to verify the behavior, but it's timeconsuming.

**Comment by stefanofornari** [comment]
Ok, thanks for your answer. how can pi-btaudio be uninstalled?

**Comment by bablokb** [comment]
First disable the pi-btaudio-service:

    sudo systemctl disable pi-btaudio.service

Then remove all installed files. These are the files below `files/` in this repositiory. Finally, remove the packages installed by the `install`-command (see list in `tools/install`).
