### ISSUE TITLE
include amixer in asound.conf

### ISSUE THREAD

**Issue by bdorer** [bablokb/pi-btaudio#5]
Thanks for this great work. It's working well. Could you provide support for amixer in your provided asound.conf? This would make it perfect.

**Comment by bablokb** [comment]
Hm, could you please elaborate on this?

**Comment by bdorer** [comment]
I'm sorry for my wrong description. I'd like to have dmixer included in asound.conf so I'm able to play 2 sounds at the same time. I looked at different wikis but couldn't find a solution.

**Comment by bablokb** [comment]
This is beyond the scope of this project. Nevertheless, this is a problem I'm also interested in. So if I have a solution, I will post a solution.

**Comment by bdorer** [comment]
https://github.com/Arkq/bluez-alsa/issues/48
Here you'll find some workarounds. It seams it isn't so easy for the developer to implement this.
