### ISSUE TITLE
`bluetoothctl` permissions

### ISSUE THREAD

**Issue by seamusdemora** [bablokb/pi-btaudio#6]
Another great repo :)  I struggled with this some time ago. I finally got it working (using `pulseaudio`), but your approach looks far easier & more elegant! 

One comment: One of the initial problems I struggled with was that RPi Lite is set up differently than RPi Desktop wrt Bluetooth. Specifically, Desktop distro includes user `pi` in the group `bluetooth`, but Lite distro does not. This required use of `sudo` to run `bluetoothctl` which in turn created other issues for me. The fix for this was adding user `pi` to group `bluetooth`: 

```bash
pi@raspberrypi4b:~ $ sudo usermod -G bluetooth -a pi 
```

This may have no relevance to your solution - just wanted to mention it.

**Comment by bablokb** [comment]
Thanks, might be helpful for others. Anyway, modern PiOS-versions move from ALSA to pulseaudio, so this repo is also somehow outdated. In my experience, bluetooth-audio does not work reliably on the Pi. Sometimes it works, then the bluetooth-stack changes a bit and it stops working. A never ending story.

**Comment by seamusdemora** [comment]
So true! It is aggravating.
