### ISSUE TITLE
Unable to install on arm64 Ubuntu 20.04 (kernel 5.4.0-1042-raspi)

### ISSUE THREAD

**Issue by sh1sh1n11** [bablokb/pi-btaudio#7]
Hi,

Thank you very much for creating this package. Unfortunately, I am unable to install this on my Raspberry Pi 4B 8GB model running kernel 5.4.0-1042-raspi ubuntu 20.04 arm64 version. Any help would be awesome! Thank you!

Below is the console output when I try to install the package. Thank you.

```
~/pi-btaudio$ sudo tools/install 
Checking bluealsa ... [INFO] installing additional packages
Hit:1 https://dtcooper.github.io/raspotify raspotify InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports focal InRelease
Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
Get:5 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease [114 kB]
Get:6 http://ports.ubuntu.com/ubuntu-ports focal-security/main arm64 c-n-f Metadata [8100 B]
Fetched 122 kB in 3s (47.7 kB/s)        
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://dtcooper.github.io/raspotify raspotify InRelease' doesn't support architecture 'arm64'
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package bluealsa
[INFO] disabling bluealsa.service
Removed /etc/systemd/system/bluetooth.target.wants/bluealsa.service.
[INFO] installing project files
[INFO] new version of configuration file saved to: /etc/asound.conf.pi-btaudio
[INFO] enabling bluealsa.service
Created symlink /etc/systemd/system/bluetooth.target.wants/bluealsa.service → /etc/systemd/system/bluealsa.service.
[INFO] enabeling pi-btaudio.service
Job for pi-btaudio.service failed because the control process exited with error code.
See "systemctl status pi-btaudio.service" and "journalctl -xe" for details.
Please edit /etc/asound.conf
Restart the system afterwards to activate changes
```

**Comment by bablokb** [comment]
Please post the relevant details:

> Job for pi-btaudio.service failed because the control process exited with error code.
> See "systemctl status pi-btaudio.service" and "journalctl -xe" for details.

I'm not sure if this works on ubuntu at all, I don't have this system. But maybe the log will give a hint.

**Comment by sh1sh1n11** [comment]
No worries bablokb. And thank you for creating the script in the first place :) In the process of getting this script running, I actually ended up learning a little bit about ALSA and Pulseaudio, which got the job done. If I may, I will go ahead and close this issue now.

**Comment by jvoosten** [comment]
In the log it shows "E: Unable to locate package bluealsa". The bluealsa  package is no longer available on RaspbianOS 11 ("Bullseye") and higher.

**Comment by bablokb** [comment]
you could try the next branch. Feedback is highly appreciated. And since this issue is closed already, maybe you might better open a new one.
