### ISSUE TITLE
Broken on Raspberry Pi OS (Lite) Bullseye

### ISSUE THREAD

**Issue by BlackYps** [bablokb/pi-btaudio#8]
On Bullseye some dependencies are not in the repositories, making the install fail and leaving you with a broken audio configuration. This should either be fixed or mentioned in the readme.

**Comment by bablokb** [comment]
please check the next branch and report back. Thanks.

**Comment by BlackYps** [comment]
I have already set up a working solution using [spotifyd](https://github.com/Spotifyd/spotifyd) in the meantime. I have no spare SD cards to test your solution and I would rather not change my setup again.
Maybe someone else that runs into this issue can test it for you.
